---
abstract: 'Guess distribution name from the current directory'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.014
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.0, Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-NameFromDirectory
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: 4.300030
  perl: 5.008001
resources:
  bugtracker: https://github.com/miyagawa/Dist-Zilla-Plugin-NameFromDirectory/issues
  homepage: https://github.com/miyagawa/Dist-Zilla-Plugin-NameFromDirectory
  repository: https://github.com/miyagawa/Dist-Zilla-Plugin-NameFromDirectory.git
version: 0.03
